USE SCHEMA DEMO;
CREATE OR REPLACE TABLE input_table(ts timestamp);

CREATE OR REPLACE TASK input_table_task_minute
  WAREHOUSE = A1SF_WH_INTERNAL_ETL_XSMALL
  SCHEDULE = '1 MINUTE'
AS
INSERT INTO input_table(ts) VALUES(CURRENT_TIMESTAMP);

EXECUTE TASK input_table_task_minute;
