USE SCHEMA DEMO;
CREATE OR REPLACE TABLE input_table_COMMON(ts timestamp);

CREATE OR REPLACE TASK input_table_COMMON_task_minute
  WAREHOUSE = A1SF_WH_INTERNAL_ETL_XSMALL
  SCHEDULE = '1 MINUTE'
AS
INSERT INTO input_table_COMMON(ts) VALUES(CURRENT_TIMESTAMP);

EXECUTE TASK input_table_COMMON_task_minute;
